In [1]:
import pandas as pd
import numpy as np

In [7]:
df=pd.read_csv('Datasets/titanic.csv')

In [8]:
df.sample(5)

Unnamed: 0  PassengerId  Survived  Pclass  \
4             4            5         0       3   
775         775          776         0       3   
6             6            7         0       1   
156         156          157         1       3   
632         632          633         1       1   

                                        Name     Sex   Age  SibSp  Parch  \
4                   Allen, Mr. William Henry    male  35.0      0      0   
775  Myhrman, Mr. Pehr Fabian Oliver Malkolm    male  18.0      0      0   
6                    McCarthy, Mr. Timothy J    male  54.0      0      0   
156         Gilnagh, Miss. Katherine "Katie"  female  16.0      0      0   
632                Stahelin-Maeglin, Dr. Max    male  32.0      0      0   

     Ticket     Fare Cabin Embarked  
4    373450   8.0500   NaN        S  
775  347078   7.7500   NaN        S  
6     17463  51.8625   E46        S  
156   35851   7.7333   NaN        Q  
632   13214  30.5000   B50        C

## Identify Categorical Features
### Specifically identify *nominal* and *ordinal* features

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Unnamed: 0   891 non-null    int64  
 1   PassengerId  891 non-null    int64  
 2   Survived     891 non-null    int64  
 3   Pclass       891 non-null    int64  
 4   Name         891 non-null    object 
 5   Sex          891 non-null    object 
 6   Age          714 non-null    float64
 7   SibSp        891 non-null    int64  
 8   Parch        891 non-null    int64  
 9   Ticket       891 non-null    object 
 10  Fare         891 non-null    float64
 11  Cabin        204 non-null    object 
 12  Embarked     889 non-null    object 
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB


# 1. Ordinal Categorical

### Here 'Embarked' is ordinal categorical

In [45]:
df['Embarked'].fillna('S', inplace=True)

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,12:],df.iloc[:,2:3],test_size=.3)

In [42]:
X_train.shape
y_train.shape

(623, 1)

In [46]:
X_train.fillna('S', inplace=True)
X_test.fillna('S',inplace=True)

## Create an OrdinalEncoder object


In [31]:
from sklearn.preprocessing import OrdinalEncoder

## Categories: Passed a list of lists

- Each list represents each column from the data.
- Each 'value' represents the total number of unique values in the column.
- Values are passed in ascending order based on the amount of value.
- For example, if we consider data of stars given to a hotel like 3-star Hotel, 5-star Hotel, 7-star Hotel, here the 7-star hotel has the maximum value.
- The encoding will be applied in the following format:
  - 3-star=0, 5-star=1, 7-star=2, and so on...
- For instance, 'S' has the minimum value, and 'Q' has the maximum value.


In [43]:
oe=OrdinalEncoder(categories=[['S','C','Q']])

# Always fit the object to 'Training Data' first and then transform training data and testing data later.


In [47]:
oe.fit(X_train)

OrdinalEncoder(categories=[['S', 'C', 'Q']])

In [48]:
X_train=oe.transform(X_train)
X_test=oe.transform(X_test)

In [58]:
X_test[0:10]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [2.],
       [1.]])

In [52]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [53]:
le.fit(y_train)
y_train=le.transform(y_train)
y_test=le.transform(y_test)

C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


#### I too didint understand what this warning said ..ignored it ;)

In [60]:
y_train[0:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0], dtype=int64)

In [59]:
y_test[0:10]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

# Done That was it..! :)